---
title: "individual1"
author: "Rabsa Naseer"
date: "11/6/2020"
output: html_document
---

```{r}
library(ggplot2)
library(readxl)
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggrepel)

acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
##acc
pers <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)
##pers

make <- readr::read_csv("makeCodes.xls")%>%
  rename("STATE" = "Codes")
##make
state <- readr::read_csv("stateCodes.xls") %>%
  rename("STATE" = "Codes")
acc2 <- right_join(state, acc)
acc_final <- right_join(make, acc2)
##acc_final <- right_join(day, acc3)
acc_final
pers2 <- right_join(make, pers)
pers_final <- right_join(state, pers2)
##pers_final

```

1. 
```{r}
table(acc_final$DAY_WEEK)
```

2.
```{r}
hurt <- pers_final[pers_final$INJ_SEV == 4,]
head(hurt)
```
3.
```{r}
col <- pers_final[, c("INJ_SEV", "MAKE", "Make", "STATE","State", "COUNTY")]
danger <- col %>%
  filter(INJ_SEV == 4) %>%
  group_by(STATE, State, MAKE, Make) %>%
  summarize(n = n()) %>%
  group_by(STATE) %>%
  filter(n == max(n)) %>%
  filter(is.na(MAKE) == FALSE) %>%
  arrange(desc(n))
head(danger)
```
4.
```{r}
codes<- readxl::read_xlsx("FRPP_GLC_-_United_StatesSep292020.xlsx")
codes <- codes[, c("State Name", "State Code", "County Code", "County Name")] %>%
  rename("STATE" = "State Code") %>%
  rename("COUNTY" = "County Code")
##codes
codes$COUNTY <- as.numeric(codes$COUNTY)

```
5.
```{r}
combo <- right_join(pers_final, acc_final)
##combo
```
6.
```{r}
combo <- combo %>%
  group_by(DAY_WEEK) %>%
  group_by(HOUR) %>%
  group_by(SEX)
head(combo)

male <- subset(combo, SEX == 1)
m_hour <- table(male$HOUR)
m_hour
m_day <- table(male$DAY_WEEK)
m_day
female <- subset(combo, SEX == 2)
f_hour <- table(female$HOUR)
f_hour
f_day <- table(female$DAY_WEEK)
f_day
```

7.
```{r}

```

8.
```{r}
summer <- combo %>%
  filter((DAY >= 20 & MONTH >= 6) & (DAY <= 22 & MONTH <= 9)) %>%
  group_by(STATE, State, MAKE, Make) %>%
  summarize(n = n()) %>%
  group_by(STATE) %>%
  filter(n == max(n)) %>%
  filter(is.na(MAKE) == FALSE) %>%
  arrange(desc(n))
summer
winter <- combo %>%
  filter((DAY >= 21 & MONTH == 12) | (DAY >= 1 & MONTH >= 1) & (DAY <= 1 & MONTH <= 3)) %>%
  group_by(STATE, State, MAKE, Make) %>%
  summarize(n = n()) %>%
  group_by(STATE) %>%
  filter(n == max(n)) %>%
  filter(is.na(MAKE) == FALSE) %>%
  arrange(desc(n))
winter
sums <- data.frame("Summer" = sum(summer$n), "Winter" = sum(winter$n))
sums
```

